# Admin modules routing configurations
cms:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   /admin/pages

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin/users

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin

# Front-end modules routing configurations
front_cms:
    resource: "@PageBundle/Controller/PageFrontController.php"
    type:     annotation
    prefix:   /
    

# Route configs related to admin login page
admin_login:
    path:     /login/{isFront}
    defaults: { _controller: AppBundle:Security:login, isFront: false }
admin_login_check:
    path: /admin/login_check
admin_logout:
    path: /admin/logout

# Route configs related to customers login page
front_login:
    path:     /shopp/login/{isFront}
    defaults: { _controller: AppBundle:Security:login, isFront: true }
front_login_check:
    path: /shopping/login_check
front_logout:
    path: /shopping/logout