# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    nesa.appService:
        class: AppBundle\Service\AppService
        public: false
        arguments: 
            - "@translator.default"
            - "@security.token_storage"
            - "@doctrine.orm.default_entity_manager"
            - "@validator"
            - "@nesa.session"
            
    nesa.md5encoder:
        class: AppBundle\Service\Md5Encoder
        arguments: 
            - "%nesa.saltmain%"
        
    nesa.session:
        class: AppBundle\Service\Session
        arguments: ~
        
    nesa.dataFixture:
        class: AppBundle\Service\DataFixture
        arguments:
            - "@nesa.appService"

    nesa.user_user:
        class: UserBundle\Service\UserService
        arguments: 
            - "@nesa.appService"
    
    nesa.printService:
        class: AppBundle\Service\PrintService
        arguments: 
            - "@nesa.hpPrinterService"
            - "@nesa.brotherPrinterService"
            - "%printerType%"
                    
    nesa.hpPrinterService:
        class: AppBundle\Service\Printer\HpPrinterService
            
    nesa.brotherPrinterService:
        class: AppBundle\Service\Printer\BrotherPrinterService 
        
    nesa.mailerService:
        class: AppBundle\Service\MailerService
        arguments: 
            - "@nesa.gmailMailerService"
            - "@nesa.outlookMailerService"
            - "%mailerType%"
                    
    nesa.gmailMailerService:
        class: AppBundle\Service\Mailer\GmailMailerService
            
    nesa.outlookMailerService:
        class: AppBundle\Service\Mailer\OutlookMailerService 
        
    nesa.loggerService:
        class: AppBundle\Service\LoggerService
        arguments: 
            - "@nesa.smsLoggerService"
            - "@nesa.fileLoggerService"
            - "@nesa.emailLoggerService"
            - "%loggerType%"
                    
    nesa.smsLoggerService:
        class: AppBundle\Service\Logger\SMSLoggerService
            
    nesa.fileLoggerService:
        class: AppBundle\Service\Logger\FileLoggerService 
        
    nesa.emailLoggerService:
        class: AppBundle\Service\Logger\EmailLoggerService 